Description of ncp
Home > core > ncp.m
ncp
PURPOSE
NCP calculates the number of control points in one dimension.
SYNOPSIS
function [ n ] = ncp(k, p)
DESCRIPTION
 NCP calculates the number of control points in one dimension.
 k: knot vector
 p: polynomial degree
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
assemble_force ASSEMBLE_FORCE assembles the right-hand side of the discrete Poisson
assemble_lb ASSEMBLE_LB assembles the stiffness matrix for the Poisson problem, i.e.,
init_cps INIT_CPS distributes the control points of a B-spline patch equally over
set_dirichlet_bc SET_DIRICHLET_BC modifies the stiffness matrix to enforce the essential
set_natural SET_NATURAL enforces the natural boundary condition along the entire
set_neumann_bc SET_NEUMANN_BC modifies the stiffness matrix as to enforce the natural or
set_zero_dirichlet SET_ZERO_DIRICHLET alters the linear system discretizing the Poisson
SOURCE CODE
function [ n ] = ncp(k, p)
% NCP calculates the number of control points in one dimension.
% k: knot vector
% p: polynomial degree
n = length(k)-p-1;
end